# # Use an official Python image
# FROM python:3.11

# # Set the working directory inside the container
# WORKDIR /app

# # Copy the Python script into the container
# COPY scrapper.py .

# # Install dependencies (if needed)
# RUN pip install --no-cache-dir psycopg2-binary requests beautifulsoup4

# # Run the scraper script when the container starts
# CMD ["python", "scrapper.py"]
